server:
  port: 8801
spring:
  application:
    name: mciroservice-customer-movie
eureka:
  client:
    serviceurl:
      defaultZone: http://peer2:8762/eureka/
    instance:
      prefer-ip-address: true